FROM golang:1.23-alpine AS builder

WORKDIR /app

ADD https://raw.githubusercontent.com/eficode/wait-for/v2.1.0/wait-for /usr/local/bin/wait-for
RUN chmod +rx /usr/local/bin/wait-for

COPY go* .

COPY ./cmd ./cmd
COPY ./config ./config
COPY ./internal ./internal
COPY ./vendor ./vendor

COPY ./scripts/entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 50051 80

ENTRYPOINT [ "/entrypoint.sh" ]